name: Convert Jupyter Notebooks to Github Pages
author: Víctor Santiago
description: Translate all Jupyter notebooks in the repository to Markdown and trigger publish
inputs:
  show-cells:
    description: Whether or not to show the code in the cells
  dependencies:
    description: Path to a file listing the requirements to run the notebooks.
    default: requirements.txt
  source:
    description: Path to the folder that contains the Notebooks

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: pip

    - name: Install project dependencies
      run: pip install -r ${{ inputs.dependencies }}
      shell: bash

    - name: Install mkdocs & material theme
      run: |
        pip install mkdocs
        pip install mkdocs-material
      shell: bash

    - name: Jupyter to Markdown Conversion
      run: |
        if [[ "${{ inputs.show-cells }}" != "" ]];
        then
          find ${{ inputs.source }} -type 'f' -name '*.ipynb' -not -name "*-checkpoint.ipynb" | xargs jupyter nbconvert --to Markdown
        else
          find ${{ inputs.source }} -type 'f' -name '*.ipynb' -not -name "*-checkpoint.ipynb" | xargs jupyter nbconvert --to Markdown --no-input
        fi;

        find ${{ inputs.source }} -type 'f' -name "*.ipynb" -delete
      shell: bash

    - name: Trigger publishing
      run: |
        mkdocs gh-deploy --clean --force
      shell: bash

branding:
  icon: archive
  color: purple
